# Default values for kubernetes_jump_pod.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: georgiivanov/kubernetes_jump_pod
  tag: latest
  pullPolicy: IfNotPresent

env:
  LOCAL_PORT: 80
  SERVICE_HOST: example.com
  SERVICE_PORT: 80

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
